#!/usr/bin/env node

var through = require('through2')
var geojsonStream = require('geojson-stream')
var argv = require('minimist')(process.argv.slice(2))

var keys = argv._

process.stdin.pipe(geojsonStream.parse())
.pipe(through.obj(write))
.pipe(geojsonStream.stringify())
.pipe(process.stdout)

function write (feat, _, next) {
  for (var i = 0; i < keys.length; i++) {
    if (feat.properties[keys[i]]) {
      feat.id = Number(feat.properties[keys[i]])
      break
    }
  }
  this.push(feat)
  next()
}
