#!/bin/bash

rm -rvf us al ak az ar ca co ct de dc fl ga hi id il in ia ks ky la me md ma mi mn ms mo mt ne nv nh nj nm ny nc nd oh ok or pa ri sc sd tn tx ut vt va wa wv wi wy as fm gu mh mp pw pr um vi

us_counties_shp() {
  mkdir -p build
  curl -z build/countyp010g.tar.gz -o build/countyp010g.tar.gz 'https://prd-tnm.s3.amazonaws.com/StagedProducts/Small-scale/data/Boundaries/countyp010g.shp_nt00934.tar.gz'
  tar -vxzm -C build -f build/countyp010g.tar.gz
  chmod a-x build/countyp010g.*
}

us_10m() {
  us_counties_shp
  mkdir -p us
  geo2topo -q 1e5 -n counties=<( \
      shp2json -n build/countyp010g.shp \
        | ndjson-filter '!/000$/.test(d.properties.ADMIN_FIPS)' \
        | ndjson-map '(d.id = d.properties.ADMIN_FIPS, delete d.properties, d)' \
        | geostitch -n \
        | geoproject -n 'd3.geoAlbersUsa().scale(1280).translate([480, 300])') \
    | toposimplify -f -p 0.3 \
    | topomerge states=counties -k 'd.id.slice(0, 2)' \
    | topomerge nation=states \
    > us/10m.json
}

ca_tracts_shp() {
  mkdir -p build
  curl -z build/tl_2016_06_tract.zip -o build/tl_2016_06_tract.zip 'https://www2.census.gov/geo/tiger/TIGER2016/TRACT/tl_2016_06_tract.zip'
  unzip -od build tl_2016_06_tract.zip
  chmod a-x build/tl_2016_06_tract.*
}

ca_tracts_500k() {
  ca_tracts_shp
  mkdir -p ca
  geo2topo -q 1e5 tracts=<( \
      shp2json -n build/tl_2016_06_tract.shp \
        | ndjson-filter '!/000$/.test(d.properties.ADMIN_FIPS)' \
        | ndjson-map '(d.id = d.properties.GEOID, delete d.properties, d)' \
        | geostitch -n \
        | ndjson-reduce 'p.features.push(d), p' '({type:"FeatureCollection",features:[]})' \
        | geoproject 'd3.geoAlbers().parallels([34, 40.5]).rotate([120, 0]).fitExtent([[10, 10], [950, 1090]], d)') \
    | toposimplify -f -p 0.3 \
    > ca/tracts-500k.json
}

ca_tracts_tsv() {
  ca_tracts_shp
  mkdir -p ca
  shp2json -n build/tl_2016_06_tract.shp \
    | ndjson-map 'd.properties' \
    | ndjson-sort 'a.GEOID.localeCompare(b.GEOID)' \
    | json2tsv -n \
    > ca/tracts.tsv
}

us_10m
